"""Sprint 6 — Compass AI Coach engine.

A thin orchestration layer *over* the deterministic Sprint 5 system:

    1. build the CoachContext through the read-only tools (6A/6D);
    2. resolve the student's intent deterministically (6B);
    3. assemble a guarded system prompt + conversation history (6C/6E);
    4. ask the injected LLMProvider for the reply (6F);
    5. mechanically validate the reply against the facts (6C);
    6. persist the turn as conversation context, never as learning truth (6E).

The engine decides HOW to coach with words generated by the LLM; every fact
it hands the LLM and every safety decision is deterministic.
"""

from __future__ import annotations

import logging
from typing import Any

from sqlalchemy.orm import Session

from app.db import crud

from . import coach_context, coach_guardrails, intent_engine

_log = logging.getLogger("arete.coach")


def actions_for_focus(focus: dict | None) -> list[str]:
    """The ONLY source of ``suggested_actions`` (Sprint 8C).

    The coach can never decide what the student should learn next — that
    decision belongs to ``adaptive_engine`` alone. These strings are
    generated deterministically from the focus step (its ``action``, target
    competency, missing prerequisites, and weak criteria), so a LEARN turn
    and a PRACTICE turn against the same evidence state produce identical
    suggested actions.
    """
    if not focus:
        return ["Course complete — no next step is required."]

    action = focus["action"]
    code = focus.get("competency_code") or ""

    if action == "complete_remediation":
        return [
            f"Finish the open remediation plan for {code}.",
            f"Then re-attempt {code} until the rubric criteria pass.",
        ]
    if action == "unlock_prerequisite":
        prereqs = focus.get("missing_prerequisites") or []
        names = ", ".join(prereqs) if prereqs else "the prerequisite"
        return [
            f"Build the foundation first: master {names}.",
            f"Return to {code} once the prerequisite is demonstrated.",
        ]
    if action == "revalidate":
        return [
            f"Re-run the simulator to re-confirm {code}.",
            "Check the latest response against every rubric criterion.",
        ]
    if action == "advance":
        return [
            f"{code} is demonstrated — move to the next competency in your learning path.",
            "Ask the coach to explain what comes next.",
        ]
    if action == "start":
        return [
            f"Begin {code} — run your first simulator attempt.",
            "Read the rubric criteria before you choose your gains.",
        ]
    # practice (the fallback rule)
    weak = focus.get("weak_criteria") or []
    targets = ", ".join(weak) if weak else "the failing rubric criteria"
    return [
        f"Re-run the simulator targeting: {targets}.",
        "Adjust your gains and re-attempt until every criterion passes.",
    ]


def _scaffolding_level(focus: dict | None) -> str:
    """Deterministic scaffolding hint from the adaptive focus."""
    action = (focus or {}).get("action")
    if action in ("complete_remediation", "practice", "revalidate"):
        return "HIGH"
    if action == "unlock_prerequisite":
        return "MEDIUM"
    return "LOW"


def _recent_history(db: Session, *, student_id: str, max_messages: int = 12) -> list[dict]:
    """Last turns of the student's active conversation (context, not truth)."""
    conv = crud.get_latest_conversation(db, student_id)
    if conv is None or not conv.messages:
        return []
    return [{"role": m.sender, "text": m.text} for m in conv.messages[-max_messages:]]


def _persist_turn(
    db: Session,
    *,
    student_id: str,
    user_message: str,
    coach_message: str,
    active_mode: str,
    scaffolding: str,
    competency_id: str | None,
) -> int:
    """Append the turn to the student's conversation (session-only state)."""
    conv = crud.get_latest_conversation(db, student_id)
    if conv is None or conv.finished:
        conv = crud.create_conversation(
            db,
            student_id=student_id,
            competency_id=competency_id,
            initial_mode=active_mode,
        )
    crud.add_message(
        db,
        conversation_id=conv.id,
        sender="student",
        text=user_message,
    )
    crud.add_message(
        db,
        conversation_id=conv.id,
        sender="coach",
        text=coach_message,
        mode=active_mode,
        scaffolding_level=scaffolding,
    )
    db.commit()
    return conv.id


async def run_coach_turn(
    db: Session,
    *,
    student_id: str,
    message: str,
    provider: Any,
    explicit_intent: str | None = None,
    mode_hint: str | None = None,
    target_competency_code: str | None = None,
    context: dict | None = None,
) -> dict:
    """Run one full coach turn and return the structured result.

    ``provider`` is any LLMProvider (the engine never picks one — 6F).
    ``context`` may be injected by tests to avoid extra DB work.
    """
    from ai_education.llm.base import LLMMessage

    ctx = context
    if ctx is None:
        student_model = coach_context.tool_student_model(db, student_id=student_id)
        focus = coach_context.tool_adaptive_focus(db, student_model=student_model)
        intent = intent_engine.resolve_intent(
            message,
            focus=focus,
            explicit_intent=explicit_intent,
            mode_hint=mode_hint,
        )
        ctx = coach_context.build_coach_context(
            db,
            student_id=student_id,
            intent_code=intent,
            intent_mode=intent_engine.MODE_BY_INTENT[intent],
            target_competency_code=target_competency_code,
        )
    else:
        intent = ctx.get("intent", {}).get("code", intent_engine.TEACH)
    active_mode = ctx.get("intent", {}).get("mode")
    if active_mode is None:
        active_mode = intent_engine.MODE_BY_INTENT[intent]

    focus = ctx.get("focus")
    target_competency_id = (focus or {}).get("competency_code") or (
        target_competency_code or "pid-tuning"
    )
    scaffolding = _scaffolding_level(focus)

    system_prompt = coach_guardrails.build_system_prompt(ctx)
    history = _recent_history(db, student_id=student_id)

    messages = [LLMMessage(role="system", content=system_prompt)]
    for turn in history:
        role = "assistant" if turn["role"] == "coach" else "user"
        messages.append(LLMMessage(role=role, content=turn["text"]))
    messages.append(LLMMessage(role="user", content=message))

    fallback_used = False
    guardrail_blocked = False
    violations: list[str] = []

    try:
        llm_response = await await_provider(provider, messages)
        reply = llm_response.content or ""
    except Exception:  # noqa: BLE001 - provider failures must not 500
        _log.warning(
            "Coach provider failed for student=%s; serving deterministic fallback",
            student_id,
            exc_info=True,
        )
        reply = coach_guardrails.fallback_message(ctx)
        fallback_used = True

    verdict = coach_guardrails.validate_reply(reply, context=ctx)
    if not verdict["ok"]:
        _log.info(
            "Coach guardrail blocked reply for student=%s: %s",
            student_id,
            verdict["violations"],
        )
        reply = coach_guardrails.fallback_message(ctx)
        guardrail_blocked = True
        violations = verdict["violations"]

    conversation_id = _persist_turn(
        db,
        student_id=student_id,
        user_message=message,
        coach_message=reply,
        active_mode=active_mode,
        scaffolding=scaffolding,
        competency_id=target_competency_id,
    )

    return {
        "conversation_id": conversation_id,
        "message": reply,
        "intent": intent,
        "active_mode": active_mode,
        "target_competency_id": target_competency_id,
        "scaffolding_level": scaffolding,
        "suggested_actions": actions_for_focus(focus),
        "guardrail_blocked": guardrail_blocked,
        "violations": violations,
        "fallback_used": fallback_used,
        "finished": focus is None,
    }


async def await_provider(provider: Any, messages: list[Any]) -> Any:
    """Call the provider's ``generate`` — async seam so tests can stub it."""
    return await provider.generate(messages)
